alias: Viomi S9 - change clean mode based on presence of mop pad
description: >-
  Automatically change the vacuum clean mode between "vacuum" and "mop"
  depending on whether the mop pad is installed or not. (installed = mop)
  vacuum.mop_state = 1 represents installed.  vacuum.wdr_mode = 0 represents
  vacuum, vacuum.wdr_mode = 1 represents vacuum & mop vacuum.wdr_mode = 2
  represents mop. Note we should not change the clean mode if cleaning is in
  progress (by checking for paused and cleaning states). To handle the change 
  of mop pad in those states, add a trigger for when the vacuum comes out of 
  those states and perform the change then.
trigger:
  - platform: state
    entity_id:
      - vacuum.viomi_v18_155a_robot_cleaner
    attribute: vacuum.mop_state
    from: 0
    to: 1
  - platform: state
    entity_id:
      - vacuum.viomi_v18_155a_robot_cleaner
    attribute: vacuum.mop_state
    from: 1
    to: 0
  - platform: state
    entity_id:
      - vacuum.viomi_v18_155a_robot_cleaner
    from:
      - paused
      - cleaning
condition:
  - condition: not
    conditions:
      - condition: template
        value_template: "{{ is_state('vacuum.viomi_v18_155a_robot_cleaner', 'paused') }}"
      - condition: template
        value_template: "{{ is_state('vacuum.viomi_v18_155a_robot_cleaner', 'cleaning') }}"
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: vacuum.viomi_v18_155a_robot_cleaner
            attribute: vacuum.mop_state
            state: 0
          - condition: state
            entity_id: vacuum.viomi_v18_155a_robot_cleaner
            attribute: vacuum.wdr_mode
            state:
              - 1
              - 2
      - condition: and
        conditions:
          - condition: state
            entity_id: vacuum.viomi_v18_155a_robot_cleaner
            attribute: vacuum.mop_state
            state: 1
          - condition: state
            entity_id: vacuum.viomi_v18_155a_robot_cleaner
            attribute: vacuum.wdr_mode
            state: 0
action:
  - variables:
      wdr_mode: >
        {% if
        is_state_attr('vacuum.viomi_v18_155a_robot_cleaner','vacuum.mop_state',
        0) %}0 {% else %}2 {% endif %}
      bdcst_msg: >
        {% if
        is_state_attr('vacuum.viomi_v18_155a_robot_cleaner','vacuum.mop_state',
        0) %}removed. Ready to vacuum. {% else %}installed. Ready to mop. {%
        endif %}
  - service: xiaomi_miot.set_property
    data:
      entity_id: vacuum.viomi_v18_155a_robot_cleaner
      field: vacuum.wdr_mode
      value: "{{ wdr_mode }}"
  - service: notify.google_assistant_sdk
    data:
      message: Viomi S9 mop pad {{ bdcst_msg }}
      target: kitchen display
mode: single
